/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author karad
 */
public class LoginPage extends javax.swing.JFrame {

    String compName = System.getProperty("user.name");
    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
      //  Image icon=new ImageIcon(this.getClass().getResource("src\\main\\java\\images\\logo.png")).getImage();
        //this.setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameLabel = new javax.swing.JLabel();
        usrTextField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        passTextField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernameLabel.setFont(new java.awt.Font("Century Schoolbook", 3, 16)); // NOI18N
        usernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usernameLabel.setText("Username");
        getContentPane().add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 151, 92, 20));

        usrTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usrTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(usrTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 205, -1));

        passwordLabel.setFont(new java.awt.Font("Century Schoolbook", 3, 16)); // NOI18N
        passwordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passwordLabel.setText("Password");
        getContentPane().add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 91, 30));

        jButton1.setText("Login");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 153, 36));
        getContentPane().add(passTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 205, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        jLabel1.setText("Perform Your Conversion Operations with One Click");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, 25));

        jLabel3.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\images\\logo.png"));
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 70, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\images\\acikyesil.png"));
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 0, 300, 427));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usrTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usrTextFieldActionPerformed

    }//GEN-LAST:event_usrTextFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        HomePage homeFrame = new HomePage();
        LoginPage loginFrame = new LoginPage();
        // Login işlemi için kontrol yapısı
        Singleton singleton = Singleton.getInstance();
        // Değeri alma
        // Değeri ayarlama
        singleton.setUsername(usrTextField.getText());
        singleton.setPassword(passTextField.getText());
        String username = Singleton.getInstance().getUsername();
        String password = Singleton.getInstance().getPassword();
        boolean loginControl = Singleton.getInstance().getLoginControl();

        if (username != null && password != null && username.equals(compName) && password.equals(compName +"123")) {
            System.out.println("Login successful!");
            loginControl = true;
        } else {
            System.out.println("Login failed!");
            loginControl = false;
        }

        if (loginControl == true){
            System.out.println(loginControl);
            //JOptionPane.showMessageDialog(null, "Welcome to The Converter App", "Login Successful!", JOptionPane.INFORMATION_MESSAGE);
            //loginFrame.setVisible(false);
            loginFrame.dispose();
            homeFrame.setVisible(true);
        }
        else{
            System.out.println(loginControl);
            JOptionPane.showMessageDialog(null, "Login Failed! Please check your validation", "Unrecognized User", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Singleton singleton = Singleton.getInstance();
                boolean loginControl = Singleton.getInstance().getLoginControl();
                HomePage homeFrame = new HomePage();
                LoginPage loginFrame = new LoginPage();
                new LoginPage().setVisible(true);
                if (loginControl == true){
                    System.out.println(loginControl);
                    //JOptionPane.showMessageDialog(null, "Welcome to The Converter App", "Login Successful!", JOptionPane.INFORMATION_MESSAGE);
                    //loginFrame.setVisible(false);
                    loginFrame.dispose();
                    homeFrame.setVisible(true);
                }   
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField passTextField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usrTextField;
    // End of variables declaration//GEN-END:variables
}
